In [27]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Numpy tasks

For a detailed reference check out: https://numpy.org/doc/stable/reference/arrays.indexing.html.

**Task 1.** Calculate the sigmoid (logistic) function on every element of the following numpy array [0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] and print the last 5 elements. Use only vector operations.

In [28]:
# Write your code here
x = np.array([0.3, 1.2, -1.4, 0.2, -0.1, 0.1, 0.8, -0.25] )
def sigmoid(z):
    return 1/(1 + np.exp(-z))

print(sigmoid(x[-5:]))

[0.549834   0.47502081 0.52497919 0.68997448 0.4378235 ]


**Task 2.** Calculate the dot product of the following two vectors:<br/>
$x = [3, 1, 4, 2, 6, 1, 4, 8]$<br/>
$y = [5, 2, 3, 12, 2, 4, 17, 11]$<br/>
a) by using element-wise mutliplication and np.sum,<br/>
b) by using np.dot,<br/>
b) by using np.matmul and transposition (y.reshape(-1, 1), the alternative y.T will not work because T does not work on 1D arrays).

In [29]:
# Write your code here
x = np.array([3,1,4,2,6,1,4,8])
y = np.array([5,2,3,12,2,4,17,11])
print(np.sum(x*y))
print(np.dot(x, y))
print(np.matmul(x, y).reshape(-1,1)[0][0])

225
225
225


**Task 3.** Calculate value of the logistic model<br/>
$$y = \frac{1}{1 + e^{-x_0 \theta_0 - \ldots - x_9 \theta_9 - \theta_{10}}}$$
for<br/>
$x = [1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2]$<br/>
$\theta = [2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65]$<br/>
and print the result. Use only vector operations.

In [30]:
# Write your code here
𝑥= np.array([1.2, 2.3, 3.4, -0.7, 4.2, 2.7, -0.5, 1.4, -3.3, 0.2, 1])
theta = np.array([2.7, 0.33, -2.12, -1.73, 2.9, -5.8, -0.9, 12.11, 3.43, -0.5, -1.65])
z = np.sum(-x*theta)
print(1/(1+np.exp(z)))

0.2417699832615572


**Task 4.** Calculate value of the multivariate linear regression model<br/>
$$y = A x + B$$
for<br/>
$A = \begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \end{bmatrix}$<br/>
$B = \begin{bmatrix} 0.2 \\ 0.3 \end{bmatrix}$<br/>
$x = [1, 2, 3]^T$<br/>
and print the result. Use only vector and matrix operations.

In [31]:
# Write your code here
A = np.array([[1, 2, 1], [3, 0, 1]])
B = np.array([[0.2], [0.3]])
x = np.array([[1, 2, 3]]).T
print(np.matmul(A, x) + B)

[[8.2]
 [6.3]]


# Pandas

## Load datasets

- Steam (https://www.kaggle.com/tamber/steam-video-games)

- MovieLens (https://grouplens.org/datasets/movielens/)

In [32]:
steam_df = pd.read_csv(os.path.join("data", "steam", "steam-200k.csv"), 
                       names=['user-id', 'game-title', 'behavior-name', 'value', 'zero'])

ml_ratings_df = pd.read_csv(os.path.join("data", "movielens_small", "ratings.csv"))
ml_movies_df = pd.read_csv(os.path.join("data", "movielens_small", "movies.csv"))

In [33]:
steam_df

user-id                  game-title behavior-name  value  zero
0       151603712  The Elder Scrolls V Skyrim      purchase    1.0     0
1       151603712  The Elder Scrolls V Skyrim          play  273.0     0
2       151603712                   Fallout 4      purchase    1.0     0
3       151603712                   Fallout 4          play   87.0     0
4       151603712                       Spore      purchase    1.0     0
...           ...                         ...           ...    ...   ...
199995  128470551                 Titan Souls          play    1.5     0
199996  128470551  Grand Theft Auto Vice City      purchase    1.0     0
199997  128470551  Grand Theft Auto Vice City          play    1.5     0
199998  128470551                        RUSH      purchase    1.0     0
199999  128470551                        RUSH          play    1.4     0

[200000 rows x 5 columns]

## Merge both MovieLens DataFrames into one

In [34]:
ml_df = pd.merge(ml_ratings_df, ml_movies_df, on='movieId')
ml_df.head(10)

userId  movieId  rating   timestamp             title  \
0       1        1     4.0   964982703  Toy Story (1995)   
1       5        1     4.0   847434962  Toy Story (1995)   
2       7        1     4.5  1106635946  Toy Story (1995)   
3      15        1     2.5  1510577970  Toy Story (1995)   
4      17        1     4.5  1305696483  Toy Story (1995)   
5      18        1     3.5  1455209816  Toy Story (1995)   
6      19        1     4.0   965705637  Toy Story (1995)   
7      21        1     3.5  1407618878  Toy Story (1995)   
8      27        1     3.0   962685262  Toy Story (1995)   
9      31        1     5.0   850466616  Toy Story (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1  Adventure|Animation|Children|Comedy|Fantasy  
2  Adventure|Animation|Children|Comedy|Fantasy  
3  Adventure|Animation|Children|Comedy|Fantasy  
4  Adventure|Animation|Children|Comedy|Fantasy  
5  Adventure|Animation|Children|Comedy|Fantasy  
6  Adventure|Animation|Children|Comedy|Fantasy  
7  Adventure|Animation|Children|Comedy|Fantasy  
8  Adventure|Animation|Children|Comedy|Fantasy  
9  Adventure|Animation|Children|Comedy|Fantasy

## Pandas tasks - Steam dataset

**Task 5.** How many people made a purchase in the Steam dataset? Remember that a person could buy many games, but you need to count every person once.

In [35]:
# Write your code here
steam_purchased = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id']]
print(len(steam_purchased.groupby('user-id').count()))

12393


**Task 6.** How many people made a purchase of "The Elder Scrolls V Skyrim"?

In [36]:
# Write your code here
steam_purchased_the_elder_scrolls_v_skyrim = steam_df.loc[(steam_df['behavior-name'] == 'purchase') & (steam_df['game-title'] == 'The Elder Scrolls V Skyrim'), ['user-id']]
print(len(steam_purchased_the_elder_scrolls_v_skyrim.groupby('user-id').count()))

717


**Task 7.** How many purchases people made on average?

In [37]:
# Write your code here
steam_purchased = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'value']]
steam_purchased = steam_purchased.groupby('user-id').agg({'value':'sum'})
print(round(steam_purchased['value'].sum()/len(steam_purchased),2))

10.45


**Task 8.** Who bought the most games?

In [38]:
# Write your code here
steam_purchased = steam_df.loc[steam_df['behavior-name'] == 'purchase', ['user-id', 'value']]
steam_purchased = steam_purchased.groupby('user-id').agg({'value':'sum'})

print(int(steam_purchased.sort_values(by='value', ascending=False).reset_index().loc[0,:].values[0]))

62990992


**Task 9.** How many hours on average people played in "The Elder Scrolls V Skyrim"?

In [39]:
# Write your code here
played_grouped = steam_df.loc[(steam_df['behavior-name'] == 'play')&(steam_df['game-title']=='The Elder Scrolls V Skyrim'), ['value']]
print(round(played_grouped['value'].sum()/len(played_grouped), 2))

104.71


**Task 10.** Which games were played the most (in terms of the number of hours played)? Display a DataFrame with the first 10 titles and respective numbers of hours.

In [40]:
# Write your code here
most_popular_games = steam_df.loc[steam_df['behavior-name']=='play', ['game-title', 'value']]
most_popular_games = most_popular_games.groupby('game-title').agg({'value': 'sum'}).sort_values(by='value', ascending=False).reset_index()
print(most_popular_games.head(10))


                                    game-title     value
0                                       Dota 2  981684.6
1              Counter-Strike Global Offensive  322771.6
2                              Team Fortress 2  173673.3
3                               Counter-Strike  134261.1
4                   Sid Meier's Civilization V   99821.3
5                        Counter-Strike Source   96075.5
6                   The Elder Scrolls V Skyrim   70889.3
7                                  Garry's Mod   49725.3
8  Call of Duty Modern Warfare 2 - Multiplayer   42009.9
9                                Left 4 Dead 2   33596.7


**Task 11.** Which games are the most consistently played (in terms of the average number of hours played)? Print a DataFrame with the first 10 titles and respective numbers of hours.

In [41]:
# Write your code here

most_popular_games = steam_df.loc[steam_df['behavior-name']=='play', ['game-title', 'value', 'user-id']]
most_popular_games = most_popular_games.groupby('game-title').agg({'value': 'sum', 'user-id':'count'}).sort_values(by='value', ascending=False)
most_popular_games['value'] = most_popular_games['value']/most_popular_games['user-id']
most_popular_games.drop('user-id', axis=1, inplace=True)
most_popular_games.sort_values(by='value', ascending=False, inplace=True)
print(most_popular_games.head(10).reset_index())


                          game-title        value
0            Eastside Hockey Manager  1295.000000
1  Baldur's Gate II Enhanced Edition   475.255556
2                    FIFA Manager 09   411.000000
3                          Perpetuum   400.975000
4              Football Manager 2014   391.984615
5              Football Manager 2012   390.453165
6              Football Manager 2010   375.048571
7              Football Manager 2011   365.703226
8                  Freaking Meatbags   331.000000
9        Out of the Park Baseball 16   330.400000


**Task 12\*\*.** Fix the above for the fact that 0 hours played is not listed, but only a purchase is recorded in such a case.

In [42]:
# Write your code here
all_games_count = steam_df.loc[(steam_df['behavior-name'] =='purchase') , ['game-title', 'user-id']]
players_number = all_games_count.groupby('game-title').agg({'user-id':'count'}).sort_values(by='game-title', ascending=False)

most_popular_games = steam_df.loc[steam_df['behavior-name']=='play', ['game-title', 'value']]
most_popular_games = most_popular_games.groupby('game-title').agg({'value': 'sum'}).sort_values(by='game-title', ascending=False)
most_popular_games['value'] = most_popular_games['value']/players_number['user-id']
most_popular_games.sort_values(by='value', ascending=False, inplace=True)
print(most_popular_games.head(10).reset_index())

                    game-title        value
0      Eastside Hockey Manager  1295.000000
1              FIFA Manager 09   411.000000
2                    Perpetuum   400.975000
3        Football Manager 2012   385.572500
4        Football Manager 2014   382.185000
5        Football Manager 2010   345.439474
6        Football Manager 2011   333.435294
7  Out of the Park Baseball 16   330.400000
8        Football Manager 2013   310.659615
9        Football Manager 2015   307.381013


**Task 13.** Apply the sigmoid function
$$f(x) = \frac{1}{1 + e^{-\frac{1}{100}x}}$$
to hours played and print a DataFrame with the first 10 rows from the entire Steam dataset after this change.

In [43]:
steam_df_copy = steam_df.copy()
steam_df_copy.loc[steam_df_copy['behavior-name'] == 'play', 'value'] = 1 / (1 + np.exp((-1/100)*steam_df_copy.loc[steam_df_copy['behavior-name'] == 'play', 'value']))
print(steam_df_copy.head(10))

     user-id                  game-title behavior-name     value  zero
0  151603712  The Elder Scrolls V Skyrim      purchase  1.000000     0
1  151603712  The Elder Scrolls V Skyrim          play  0.938774     0
2  151603712                   Fallout 4      purchase  1.000000     0
3  151603712                   Fallout 4          play  0.704746     0
4  151603712                       Spore      purchase  1.000000     0
5  151603712                       Spore          play  0.537181     0
6  151603712           Fallout New Vegas      purchase  1.000000     0
7  151603712           Fallout New Vegas          play  0.530213     0
8  151603712               Left 4 Dead 2      purchase  1.000000     0
9  151603712               Left 4 Dead 2          play  0.522235     0


## Pandas tasks - MovieLens dataset

**Task 14\*.** Calculate popularity (by the number of users who watched a movie) of all genres. Print a DataFrame with two columns: genre, n_users, where n_users contains the number of users who watched a given genre. Sort all genres in descending order.

In [44]:
ml_movies_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [45]:
ml_ratings_df.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [46]:
# Write your code here
df = ml_df.copy()
df['genres'] = df["genres"].str.split("|", expand = False)
df = df.explode("genres")
df = df.rename(columns={'genres': 'genre'})
df = df.groupby('genre').agg({'userId':'count'}).sort_values(by='userId', ascending=False).rename(columns = {'userId': 'n_users'})
print(df.reset_index())

                 genre  n_users
0                Drama    41928
1               Comedy    39053
2               Action    30635
3             Thriller    26452
4            Adventure    24161
5              Romance    18124
6               Sci-Fi    17243
7                Crime    16681
8              Fantasy    11834
9             Children     9208
10             Mystery     7674
11              Horror     7291
12           Animation     6988
13                 War     4859
14                IMAX     4145
15             Musical     4138
16             Western     1930
17         Documentary     1219
18           Film-Noir      870
19  (no genres listed)       47


**Task 15\*.** Calculate average rating for all genres. Print a DataFrame with two columns: genre, rating, where rating contains the average rating for a given genre. Sort all genres in descending order.

In [48]:
# Write your code here
df = ml_df.copy()
df['genres'] = df["genres"].str.split("|", expand = False)
df = df.explode("genres")
df = df.rename(columns={'genres': 'genre'})
df = df.groupby('genre').agg({'userId':'count', 'rating':'sum'}).rename(columns = {'userId': 'n_users'})
df['rating'] = df['rating']/df['n_users']
df = df.drop('n_users', axis=1).sort_values('rating', ascending=False)
print(df.reset_index())

                 genre    rating
0            Film-Noir  3.920115
1                  War  3.808294
2          Documentary  3.797785
3                Crime  3.658294
4                Drama  3.656184
5              Mystery  3.632460
6            Animation  3.629937
7                 IMAX  3.618335
8              Western  3.583938
9              Musical  3.563678
10           Adventure  3.508609
11             Romance  3.506511
12            Thriller  3.493706
13             Fantasy  3.491001
14  (no genres listed)  3.489362
15              Sci-Fi  3.455721
16              Action  3.447984
17            Children  3.412956
18              Comedy  3.384721
19              Horror  3.258195


**Task 16.** Calculate each movie rating bias (deviation from the mean of all movies average rating). Print a DataFrame with the first 10 in the form: title, average rating, bias.

In [49]:
# Write your code here
movie_rating_bias_df = ml_movies_df.merge(ml_ratings_df, on='movieId')
movie_rating_bias_df = movie_rating_bias_df.groupby('title').agg({'rating': 'sum', 'movieId':'count'}).reset_index()
movie_rating_bias_df['average_rating'] = movie_rating_bias_df['rating']/movie_rating_bias_df['movieId']
all_movies_avg_rating = ml_ratings_df['rating'].mean()
movie_rating_bias_df['bias'] = movie_rating_bias_df['average_rating'] - all_movies_avg_rating
movie_rating_bias_df = movie_rating_bias_df[['title', 'average_rating', 'bias']]
print(movie_rating_bias_df.head(10))

                                     title  average_rating      bias
0                               '71 (2014)        4.000000  0.498443
1  'Hellboy': The Seeds of Creation (2004)        4.000000  0.498443
2                   'Round Midnight (1986)        3.500000 -0.001557
3                      'Salem's Lot (2004)        5.000000  1.498443
4                'Til There Was You (1997)        4.000000  0.498443
5          'Tis the Season for Love (2015)        1.500000 -2.001557
6                       'burbs, The (1989)        3.176471 -0.325086
7                     'night Mother (1986)        3.000000 -0.501557
8              (500) Days of Summer (2009)        3.666667  0.165110
9           *batteries not included (1987)        3.285714 -0.215843


**Task 17.** Calculate each user rating bias (deviation from the mean of all users average rating). Print a DataFrame with the first 10 in the form: user_id, average rating, bias.

In [50]:
# Write your code here
user_rating_bias_df = ml_ratings_df.groupby('userId').agg({'rating':'sum', 'movieId':'count'}).reset_index()
user_rating_bias_df['average_rating'] = user_rating_bias_df['rating']/user_rating_bias_df['movieId']
all_users_avg_rating = ml_ratings_df['rating'].mean()
user_rating_bias_df['bias'] = user_rating_bias_df['average_rating']-all_users_avg_rating
user_rating_bias_df = user_rating_bias_df[['userId','average_rating','bias']]
print(user_rating_bias_df.head(10))

   userId  average_rating      bias
0       1        4.366379  0.864822
1       2        3.948276  0.446719
2       3        2.435897 -1.065660
3       4        3.555556  0.053999
4       5        3.636364  0.134807
5       6        3.493631 -0.007926
6       7        3.230263 -0.271294
7       8        3.574468  0.072911
8       9        3.260870 -0.240687
9      10        3.278571 -0.222986


**Task 18.** Randomly choose 10 movies and 10 users and print their interaction matrix in the form of a DataFrame with user_id as index and movie titles as columns. You can iterate over the DataFrame in this task. Alternatively, try using the DataFrame pivot and reindex methods and compare the execution time. Initialize the numpy random number generator with seed=4321.

In [74]:
# Write your code here
user_ids = ml_df['userId'].unique()
movie_ids = ml_df['movieId'].unique()
rng = np.random.RandomState(seed=4321)
user_ids = sorted(list(rng.choice(user_ids, size=10)))
movie_ids = sorted(list(rng.choice(movie_ids, size=10)))

ml_df_inter_matrix = ml_df[ml_df.movieId.isin(movie_ids)]
ml_df_inter_matrix = ml_df_inter_matrix[ml_df_inter_matrix.userId.isin(user_ids)][['userId', 'title']]
ml_df_inter_matrix_output = pd.DataFrame(0.0, index=user_ids, columns=ml_df[ml_df.movieId.isin(movie_ids)].sort_values(by='movieId')['title'].unique())

for row in ml_df_inter_matrix.itertuples():
    ml_df_inter_matrix_output.loc[row.userId, row.title] = 1.0

print(ml_df_inter_matrix_output)

     Father of the Bride (1950)  Matrix, The (1999)  Howards End (1992)  \
11                          0.0                 0.0                 0.0   
277                         0.0                 0.0                 0.0   
286                         0.0                 1.0                 0.0   
357                         0.0                 0.0                 0.0   
414                         0.0                 1.0                 0.0   
428                         0.0                 1.0                 0.0   
470                         0.0                 0.0                 0.0   
487                         0.0                 1.0                 0.0   
543                         0.0                 1.0                 0.0   
544                         0.0                 0.0                 0.0   

     Thirteen Conversations About One Thing (a.k.a. 13 Conversations) (2001)  \
11                                                 0.0                         
277           

## Pandas + numpy tasks

**Task 19.** Create the entire interaction matrix (2D numpy array) for the MovieLens dataset. Print the submatrix of the first 10 rows and 10 columns.

In [113]:
# Write your code here
def func_1(x):
    return int(x.values[0] > 0)

table_df = ml_df.loc[ml_df['userId'] > 0, ['userId', 'movieId', 'title', 'rating']].pivot_table(index='userId', columns=['movieId', 'title'], aggfunc=func_1, fill_value=0).iloc[:9, :9]
table_df.columns = table_df.columns.map(lambda x: x[2])

result = np.zeros((10, 10))
result[1:10, 1:10] = table_df

print(result)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Task 20.** Calculate the matrix of size (n_users, n_users) where at position (i, j) there is the number of movies watched both by user i and user j. Use a single matrix multiplication to obtain the result. Print the submatrix of first 10 rows and 10 columns.

In [72]:
# Write your code here
def count_movies(movies_1, movies_2):
    return len(set(movies_1) & set(movies_2))


movie_n_users_df = ml_df[['userId', 'movieId']].groupby(['userId'])['movieId'].apply(list).to_frame()

new_movie_n_users_df = pd.concat([ml_df[['userId', 'movieId']].groupby(['userId'])['movieId'].apply(list).to_frame(),
                                  pd.DataFrame(columns=ml_df['userId'].unique(), index=ml_df['userId'].unique(), dtype=int)], 
                                  axis=1).fillna(0)

n_users = len(movie_n_users_df)

n_users_matrix = np.zeros((n_users+1, n_users+1))

for row_1 in new_movie_n_users_df.itertuples():
    n_users_matrix[row_1.Index, row_1.Index] = len(row_1.movieId)
    for row_2 in movie_n_users_df[row_1.Index:].itertuples():
        n_users_matrix[row_2.Index, row_1.Index] = count_movies(row_1.movieId, row_2.movieId)
        n_users_matrix[row_1.Index, row_2.Index] = count_movies(row_1.movieId, row_2.movieId)

print(n_users_matrix[:10, :10])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 232.   2.   7.  45.  13.  33.  26.  15.   5.]
 [  0.   2.  29.   0.   1.   1.   2.   3.   1.   0.]
 [  0.   7.   0.  39.   1.   1.   3.   0.   1.   0.]
 [  0.  45.   1.   1. 216.  12.  27.  22.   9.   1.]
 [  0.  13.   1.   1.  12.  44.  36.   9.  19.   0.]
 [  0.  33.   2.   3.  27.  36. 314.  14.  44.   2.]
 [  0.  26.   3.   0.  22.   9.  14. 152.   8.   6.]
 [  0.  15.   1.   1.   9.  19.  44.   8.  47.   0.]
 [  0.   5.   0.   0.   1.   0.   2.   6.   0.  46.]]


**Task 21.** Calculate the matrix of size (n_items, n_items) where at position (i, j) there is the number of users who watched both movie i and movie j. Use a single matrix multiplication to obtain the result. To prevent memory error use only the first 1000 items. Print the submatrix of first 10 rows and 10 columns.

In [89]:
# Write your code here
def count_users(users_1, users_2):
    return len(set(users_1) & set(users_2))

users_n_items_df = ml_df[['userId', 'movieId']].groupby(['movieId'])['userId'].apply(list).to_frame()[:9]

n_items_matrix = np.zeros((10, 10))

for row_1 in users_n_items_df.itertuples():
    n_items_matrix[row_1.Index, row_1.Index] = len(row_1.userId)
    for row_2 in users_n_items_df[row_1.Index:].itertuples():
        n_items_matrix[row_2.Index, row_1.Index] = count_users(row_1.userId, row_2.userId)
        n_items_matrix[row_1.Index, row_2.Index] = count_users(row_1.userId, row_2.userId)

print(n_items_matrix[:10, :10])

[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 215.  68.  32.   2.  32.  58.  32.   5.  12.]
 [  0.  68. 110.  26.   3.  22.  36.  18.   6.   3.]
 [  0.  32.  26.  52.   1.  19.  25.  19.   4.   9.]
 [  0.   2.   3.   1.   7.   3.   2.   6.   1.   0.]
 [  0.  32.  22.  19.   3.  49.  24.  23.   4.   9.]
 [  0.  58.  36.  25.   2.  24. 102.  22.   5.   9.]
 [  0.  32.  18.  19.   6.  23.  22.  54.   4.   5.]
 [  0.   5.   6.   4.   1.   4.   5.   4.   8.   0.]
 [  0.  12.   3.   9.   0.   9.   9.   5.   0.  16.]]
